### ISSUE TITLE
Clicking on <All> removes all the names

### ISSUE THREAD

**Issue by frosas** [Erwin6997/baby-names-react#2]
Instead, all the names (that are filtered by the input box) should be shown.

https://github.com/Erwin6997/baby-names-react/blob/d8643baddef55486756873c586fb984791800283/src/All.js#L3-L14

**Comment by Erwin6997** [comment]
I need help with this part. tries to show all the data but I couldn't because the didn't accept space in.

**Comment by Erwin6997** [comment]
I fix it but I don't think its correct way to fix.

**Comment by frosas** [comment]
I think this can be closed now
