### ISSUE TITLE
<Girl>, <All> and <Boy> shouldn't need to access `data` or `setBabyName`

### ISSUE THREAD

**Issue by frosas** [Erwin6997/baby-names-react#3]
https://github.com/Erwin6997/baby-names-react/blob/d8643baddef55486756873c586fb984791800283/src/App.js#L38-L40

**Comment by Erwin6997** [comment]
yes its Doesn’t need Data but I need setBabyName on

**Comment by frosas** [comment]
Closing this as you already changed it
