### ISSUE TITLE
Active gender button doesn't appear active

### ISSUE THREAD

**Issue by frosas** [Erwin6997/baby-names-react#6]
According to the exercise,

> The buttons should operate as "radio" buttons - exactly one should be active at any time.

> The app should make it clear which filter is in effect.

Something as subtle as in the exercise example would do:

![level-4](https://user-images.githubusercontent.com/50098/84589399-24f13800-ae26-11ea-8c8f-ef9359e0c636.png)

**Comment by Erwin6997** [comment]
ok. I will change it

**Comment by frosas** [comment]
Closing this issue as it works as expected now.

Note though you could also have changed the (CSS) style of the images you had before when they were selected (by adding them a border, for example) instead of replacing them with an `<input type="radio">`

**Comment by frosas** [comment]
By the way, you forgot to select the initially selected radio button ("All") when the page loads
